### ISSUE TITLE
Update life cycle stage?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/bioc-rnaseq#101]
Is _pre-alpha_ still the most appropriate description of the maturity of this lesson? Looking through the lesson site, the content looks quite mature, and if I recall correctly it has been taught a few times already? If so, it would be better marked as _alpha_ or even _beta_, if you think it is ready for other Instructors to use.

**Comment by csoneson** [comment]
Thanks! As discussed in the meeting today, I have changed the lifecycle stage to 'beta' (https://github.com/carpentries-incubator/bioc-rnaseq/pull/102)
