### ISSUE TITLE
Upstream changes are not pushed anymore

### ISSUE THREAD

**Issue by csoneson** [carpentries-incubator/bioc-rnaseq#113]
Not quite sure where to file this issue, so I figured I try here, and tag people who may have an idea (perhaps @tobyhodges, @ErinBecker, @jdrnevich, @kevinrue, @lgatto?)

It seems that this repository is no longer receiving the automatic updates from the carpentries bot. Originally, I think it was due to the GitHub Actions workflow building the lesson failing (because of an issue with installing one of the packages) - I believe that I have fixed this a few weeks ago (I had to run an update of the environment locally, see 194df52), but it seems this did not bring the updates back. This morning the other two Bioc lessons received an update of the `sandpaper` version (https://github.com/carpentries-incubator/bioc-intro/pull/135, https://github.com/carpentries-incubator/bioc-project/pull/100), so I think there should have been something pushed also to this repository. 

In case anyone knows whether there are other things I should change, or if I should reach out to someone else, I'd be happy for any feedback. 

Thanks in advance!

**Comment by froggleston** [comment]
Hi @csoneson - I believe this is due to the relevant workflow actions being disabled for your repository:
![image](https://github.com/user-attachments/assets/7cceb112-2e08-4d80-bf9a-e301acb3d418)

If you reenable these, you should start to see updates again. Please let us know if not!

**Comment by csoneson** [comment]
@froggleston Oh my - that does seem plausible, thank you! I should have seen that. I enabled the workflows again. I then tried to start the `01 Build and Deploy Site` and immediately ran into an error, but that may be because some files are outdated - perhaps it makes sense to wait for the next upstream update and see how that goes. Thanks!

**Comment by csoneson** [comment]
Looks like today's update went through and the Actions are all green, so I'll close this issue 🙂 Thanks again!
