### ISSUE TITLE
Collapse 4-5 Intro/Set up sections into 3

### ISSUE THREAD

**Issue by jdrnevich** [carpentries-incubator/bioc-rnaseq#38]
We currently have the github.io landing page titled "Summary and Setup", then episodes "Introduction and setup", "Introduction to RNA-seq" and "Setup". These should be condensed to be less redundant. Possible suggestion:

Landing page "Summary and Setup" has 
- [ ] #39
- [ ] Overview of the lessons
- [ ] Prerequisites
- [ ] Directions on installing/updating R & RStudio and what packages to install. Attendees are supposed to do this ahead of the workshop, not during the workshop although instructors can be available prior to the workshop to help.

Episode 1: "Introduction to RNA-Seq" has:
- [ ] Explain what RNA-seq is.
- [ ] Describe some of the most common design choices that have to be made before running an RNA-seq experiment.
- [ ] Provide an overview of the procedure to go from the raw data to the read count matrix that will be used for downstream analysis.
- [ ] Show some common types of results and visualizations generated in RNA-seq analyses.

Episode 2: "RStudio Project and Experimental Data" has:

- [ ] Instructions to set up RStudio project and directory structure (can reuse https://carpentries-incubator.github.io/bioc-intro/20-r-rstudio.html#getting-set-up)
- [ ] Introduce example data set and download

Episode 3 "Experimental design"

- [ ] Reviewer larger experiment and see how to parameterize it in various ways
- [ ] Subset down to 2 X 2 for rest of workshop
- [ ] Read in subset data and put into SE

Episode 4: "Exploratory analysis and quality control" (previous episode 6)

**Comment by ghar1821** [comment]
@jdrnevich, I can do the tasks for Episode 2. Should I create a new github issue for that and assign it to myself?

**Comment by jdrnevich** [comment]
Yes. But wait until I do the reorganization. I should be able to get to it this morning. Thanks for your help, @ghar1821 !

**Comment by jdrnevich** [comment]
@ghar1821 the reorg is all finished. I also already uploaded the data sets to this repository and fixed the download links. The original links had "?raw=true" at the end. I have no idea what this means so I took it off one to see what would happen, but I haven't tested it yet. But the site seems to render just fine.

**Comment by ghar1821** [comment]
Great! I'll pull your latest updates and start working on episode 2. New Github issue incoming as well.

**Comment by ghar1821** [comment]
@jdrnevich just finished writing up episode 2. Pull request here: https://github.com/carpentries-incubator/bioc-rnaseq/pull/47. Let me know what you and the team think :)

**Comment by jdrnevich** [comment]
Looks amazing! I made a recommendation for one small change in the pull request comments #47 . I am going on vacation later today until June 12, so if you haven't made it by then I'll just approve this pull request to get the expanded section up now.
