### ISSUE TITLE
Not recognizing .Rmd files in episodes directory?

### ISSUE THREAD

**Issue by jdrnevich** [carpentries-incubator/bioc-rnaseq#43]
@lgatto @csoneson asking you this before kicking it upstairs. I tried to do the re-organization/collapse of the episodes which involved re-naming most of the espisode .Rmd files, which I did with `git mv`. All seemed to go well but when I made the pull request https://github.com/carpentries-incubator/bioc-rnaseq/actions/runs/5003856029/jobs/8965634091?pr=42 there is an error that `The /home/runner/work/bioc-rnaseq/bioc-rnaseq/episodes directory must have (R)markdown files`. I get the same error when I try to build locally:
```
> sandpaper::serve()
Error: The C:/GitHubRepos/bioc-rnaseq/episodes directory must have (R)markdown files
```
The files all have .Rmd so what could be the problem?

**Comment by jdrnevich** [comment]
I did make a change/commit to every single .Rmd file in the episodes directory...

**Comment by csoneson** [comment]
I think you need to modify also the `config.yaml` file (see [here](https://github.com/carpentries-incubator/bioc-rnaseq/pull/20/files) for example, I think I had the same issue ther)

**Comment by jdrnevich** [comment]
Thanks @csoneson ! I guess that makes sense - I was wondering how it knew to organize them. Just putting 01, 02 at the beginning of the episode file name seemed a little too simple. That seemed to work, although now I have some error in your experimental design page that I moved to the end. I'll look to see what happened...

BTW - on the landing page https://carpentries-incubator.github.io/bioc-rnaseq/index.html, any idea where the "Check you have the most recent versions of R..." part lives? It isn't in the index.md file like the top stuff is.

**Comment by csoneson** [comment]
I think it's in learners/setup.md

**Comment by jdrnevich** [comment]
Got the reorg all done!
