### ISSUE TITLE
Manually update workflow files. 

### ISSUE THREAD

**Issue by zkamvar** [carpentries-incubator/bioc-rnaseq#45]
Hello, I noticed that https://github.com/carpentries-incubator/bioc-rnaseq/actions/runs/5116496804 is failing due to an error in the JS of a dependency.

This will prevent updates to the package cache and the workflows from coming in. Please follow the instructions at https://carpentries.github.io/sandpaper-docs/update.html#via-r to update the workflows using the latest version of {sandpaper}.

Note: this is also an issue for the other bioc repositories as well.

**Comment by jdrnevich** [comment]
Thanks, @zkamvar for noticing this and giving a link to detailed fix instructions! I merged the pull request with the updates and the action is running. Hopefully that fixes the problem for this bioc repository.
