### ISSUE TITLE
suggest episode re-order to 5. DE analysis, 6. Exploration of design matrices, 7. Re-visit practice data analysis, 8. Gene set

### ISSUE THREAD

**Issue by jdrnevich** [carpentries-incubator/bioc-rnaseq#73]
At the BioC2023 workshop, I jumped from episode 5 DE analysis to episode 8 to explore design matrices. My rationale was that episode 5 was just showing the mechanics of how DESeq2 works and how to pull out contrasts and to that end we had to throw in a design matrix of some sort without actually really considering what the coef/contrasts were measuring. [edited out something I had wrong before!]

I think we could leave episode 5 mostly as it is, but kind of gloss over what each coef/contrast is measuring other than generally time differences or sex differences. Then use ExploreModelMatrix to figure out what it was actually measuring, stepping through the simple to the more complex. Then write a new episode of how to analyze the dataset depending on what information/contrasts do we want and how to pull them out. Show examples of using DESeq2's `contrast = c("time","Day8","Day0")` but possibly as a single factor with 6 levels to easily pull out specific pairwise comparisons. And maybe even how to do an interaction test. [NOTE: when I live-coded this in class, I resorted to limma's `makeContrasts()` in order to get a numeric contrast vector to give to `contrast =`.

In episode 5 I also added in an example of how to write out your results to a .csv or .tsv file (Examples in Day2_08-01-2023.R at https://uofi.box.com/s/o71rrvlfqb84seewl4n31wqkif13uy12)

FINAL THOUGHT: Also could go from episode 1, experimental design, directly into ExploreModelMatrix. The rationale being you need to understand how you will analyze your experiment before you actually conduct your experiment to make sure you don't confound anything or can't answer the question you are trying to answer. ExploreModelMatrix doesn't need data, just hypothetical samples belonging to various experimental factors. **However, this could possibly break the attendees' brains by having it so early!**

**Comment by csoneson** [comment]
I reordered the episodes according to this suggestion in https://github.com/carpentries-incubator/bioc-rnaseq/pull/76
